### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by stampFabian** [stampFabian/AutoLogin#138]
via

-EMail
-SMS
-2FA

**Comment by AdamKITZ** [comment]
Possibility to add 2fa at login will be added.

will be via E-Mail; no sms

- create a checkbox or something to give user ability to enable 2FA

**Comment by AdamKITZ** [comment]
Shall we even give the option to enable/disable 2FA or shall it be 'always-on'
might be better

**Comment by AdamKITZ** [comment]
2FA will be ALWAYS ON when logging in.
Added in  #155
